# Project Information
site_name: Maghreb vACC Documentation
site_url: https://docsv2.vatsim.ma
site_author: Bobbie Chell
repo_url: https://github.com/MAGvACC/documentation-v2
repo_name: MAGvACC/documentation-v2
edit_uri: ""
copyright: Copyright © 2023 Maghreb vACC

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: https://cdn.discordapp.com/attachments/991795403093721108/1118961763577237514/test.png
  font:
    text: Lato
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  favicon: https://cdn.discordapp.com/attachments/991795403093721108/1118961763577237514/test.png
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: en
  - awesome-pages
  - git-revision-date-localized:
      type: date

# Styling Front-end
extra_css:
  - stylesheets/extra.css
  - stylesheets/admonitions.css
  - stylesheets/navigation.css

# Extra Functions / Customizations
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/maghrebvacc/
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MaghrebvACC
    - icon: fontawesome/brands/discord
      link: https://community.vatsim.net/servers
    - icon: material/home
      link: https://vatsim.ma
      name: Home

# Additional Markdown Extensions
markdown_extensions:
  - meta
  - admonition
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - abbr
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js